# Copyright 2025-present DatusAI, Inc.
# Licensed under the Apache License, Version 2.0.

"""DAG source-code generator for the Datus Airflow adapter.

The generated DAG embeds the SQL + connection config as a JSON literal inside
the Python source.  The only Airflow-native dependency is ``sqlalchemy``, which
ships with every Airflow installation.
"""

import json
import logging
import textwrap
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)


_SPARK_DAG_TEMPLATE = textwrap.dedent(
    '''\
    # ============================================================
    # Auto-generated by Datus Airflow Adapter — DO NOT EDIT
    # Job  : {job_name}
    # Built: {built_at}
    # ============================================================

    from __future__ import annotations

    import json
    from datetime import datetime, timezone

    from airflow import DAG
    from airflow.operators.python import PythonOperator

    _SPARK_CONFIG: dict = {config_json}


    def _run_spark_script(**context: dict) -> None:  # noqa: ANN001
        """Execute the PySpark script configured by Datus."""
        import os

        os.environ.setdefault("SPARK_LOCAL_IP", "127.0.0.1")
        from pyspark import SparkConf, SparkContext  # noqa: PLC0415

        conf = SparkConf().setMaster(_SPARK_CONFIG["spark_master"]).setAppName("DatusSparkJob")
        sc = SparkContext.getOrCreate(conf=conf)
        local_vars = {{"sc": sc}}
        exec(_SPARK_CONFIG["spark_script"], local_vars)  # noqa: S102
        sc.stop()


    with DAG(
        dag_id={dag_id_repr},
        description={description_repr},
        schedule={schedule_repr},
        start_date=datetime({start_year}, {start_month}, {start_day}, tzinfo=timezone.utc),
        end_date={end_date_repr},
        catchup=False,
        tags=["datus", "spark"],
        is_paused_upon_creation=False,
    ) as dag:
        run_spark = PythonOperator(
            task_id="run_spark_script",
            python_callable=_run_spark_script,
        )
    '''
)


_DAG_TEMPLATE = textwrap.dedent(
    '''\
    # ============================================================
    # Auto-generated by Datus Airflow Adapter — DO NOT EDIT
    # Job  : {job_name}
    # Built: {built_at}
    # ============================================================

    from __future__ import annotations

    import json
    from datetime import datetime, timezone

    from airflow import DAG
    from airflow.operators.python import PythonOperator

    _DATUS_CONFIG: dict = {config_json}


    def _airflow_connection(db_connection: dict):
        conn_id: str | None = db_connection.get("conn_id")
        if not conn_id:
            return None

        from airflow.hooks.base import BaseHook  # noqa: PLC0415

        return BaseHook.get_connection(conn_id)


    def _connection_extra(conn) -> dict:
        if conn is None:
            return {{}}
        extra = conn.extra_dejson if hasattr(conn, "extra_dejson") else {{}}
        return extra or {{}}


    def _is_duckdb_iceberg_connection(db_connection: dict) -> bool:
        conn = _airflow_connection(db_connection)
        extra = _connection_extra(conn)
        executor = str(extra.get("datus_executor") or extra.get("executor") or "").lower()
        conn_type = str(getattr(conn, "conn_type", "") or "").lower()
        return executor == "duckdb_iceberg" or conn_type == "duckdb_iceberg"


    def _resolve_connection_url(db_connection: dict) -> str | None:
        """Resolve a SQLAlchemy connection URL from db_connection config.

        Supports two modes:
          - conn_id: reference an Airflow-managed Connection (preferred)
          - url: explicit SQLAlchemy URL (legacy / testing)
        """
        conn_id: str | None = db_connection.get("conn_id")
        if conn_id:
            conn = _airflow_connection(db_connection)
            # DuckDB: Airflow round-trips the URI through component parsing,
            # which can corrupt "duckdb:///path".  Rebuild from conn fields.
            if conn.conn_type == "duckdb":
                from urllib.parse import urlencode  # noqa: PLC0415

                db_path = conn.schema or conn.host or ""
                if not db_path:
                    raise ValueError(
                        "[Datus] Airflow connection '" + conn_id + "' has conn_type=duckdb "
                        "but no database path in schema or host fields."
                    )
                if db_path == ":memory:":
                    url = "duckdb:///:memory:"
                elif db_path.startswith("/"):
                    url = "duckdb:///" + db_path      # absolute: duckdb:////abs/path
                else:
                    url = "duckdb:///" + db_path       # relative: duckdb:///local.db
                # Preserve query parameters from Airflow extras
                query_params = conn.extra_dejson if hasattr(conn, "extra_dejson") else {{}}
                if query_params:
                    url = url + "?" + urlencode(query_params, doseq=True)
                print("[Datus] Using Airflow connection: " + conn_id + " (duckdb)")
                return url
            url = conn.get_uri()
            # Airflow returns "postgres://" but SQLAlchemy 1.4+ requires "postgresql://"
            if url.startswith("postgres://"):
                url = "postgresql://" + url[len("postgres://"):]
            print("[Datus] Using Airflow connection: " + conn_id)
            return url

        return db_connection.get("url")


    def _load_duckdb_extension(conn, name: str) -> None:
        try:
            conn.execute("LOAD " + name)
        except Exception:
            conn.execute("INSTALL " + name)
            conn.execute("LOAD " + name)


    def _bool_extra(value, default: bool = False) -> bool:
        if value is None:
            return default
        if isinstance(value, bool):
            return value
        return str(value).strip().lower() in {{"1", "true", "yes", "on"}}


    def _quote_sql_literal(value: object) -> str:
        return "'" + str(value).replace("'", "''") + "'"


    def _safe_identifier(value: object, field_name: str) -> str:
        import re  # noqa: PLC0415

        text = str(value)
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", text):
            raise ValueError("[Datus] Invalid " + field_name + ": " + text)
        return text


    def _sql_option(name: str, value: object) -> str | None:
        if value is None or value == "":
            return None
        if isinstance(value, bool):
            return name + " " + ("true" if value else "false")
        return name + " " + _quote_sql_literal(value)


    def _create_iceberg_secret_if_needed(con, extra: dict) -> str | None:  # noqa: ANN001
        secret_name = extra.get("iceberg_secret_name") or extra.get("catalog_secret_name") or extra.get("secret_name")
        create_secret = _bool_extra(extra.get("create_iceberg_secret"), default=True)
        credential_keys = {{
            "client_id",
            "client_secret",
            "oauth2_server_uri",
            "oauth2_scope",
            "oauth2_grant_type",
            "token",
        }}
        has_credentials = any(extra.get(key) for key in credential_keys)
        if not secret_name and has_credentials:
            secret_name = "datus_iceberg"
        if not secret_name:
            return None

        secret_name = _safe_identifier(secret_name, "iceberg_secret_name")
        if not create_secret:
            return secret_name

        secret_option_map = {{
            "client_id": "CLIENT_ID",
            "client_secret": "CLIENT_SECRET",
            "oauth2_server_uri": "OAUTH2_SERVER_URI",
            "oauth2_scope": "OAUTH2_SCOPE",
            "oauth2_grant_type": "OAUTH2_GRANT_TYPE",
            "token": "TOKEN",
        }}
        secret_parts = ["TYPE iceberg"]
        for cfg_key, sql_name in secret_option_map.items():
            option = _sql_option(sql_name, extra.get(cfg_key))
            if option:
                secret_parts.append(option)
        if len(secret_parts) == 1:
            return secret_name

        con.execute("CREATE OR REPLACE SECRET " + secret_name + " (" + ", ".join(secret_parts) + ")")
        return secret_name


    def _rewrite_iceberg_create_or_replace_table(sql: str) -> str:
        import re  # noqa: PLC0415

        pattern = re.compile(
            r"CREATE\\s+OR\\s+REPLACE\\s+TABLE\\s+"
            r"([A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*)\\s+AS",
            re.IGNORECASE,
        )
        return pattern.sub(
            lambda match: "DROP TABLE IF EXISTS "
            + match.group(1)
            + ";\\nCREATE TABLE "
            + match.group(1)
            + " AS",
            sql,
        )


    def _execute_duckdb_iceberg_sql(sql: str, db_connection: dict) -> dict:
        conn = _airflow_connection(db_connection)
        if conn is None:
            raise ValueError("[Datus] duckdb_iceberg execution requires db_connection.conn_id")

        extra = _connection_extra(conn)
        catalog_alias = _safe_identifier(extra.get("catalog_alias") or "lake", "catalog_alias")
        catalog_uri = extra.get("iceberg_catalog_uri") or extra.get("catalog_uri") or extra.get("endpoint")
        warehouse = extra.get("warehouse")
        if not catalog_uri:
            raise ValueError("[Datus] duckdb_iceberg connection extra requires iceberg_catalog_uri")
        if not warehouse:
            raise ValueError("[Datus] duckdb_iceberg connection extra requires warehouse")

        import duckdb  # noqa: PLC0415

        con = duckdb.connect(":memory:")
        try:
            _load_duckdb_extension(con, "httpfs")
            _load_duckdb_extension(con, "iceberg")

            iceberg_secret_name = _create_iceberg_secret_if_needed(con, extra)

            key_id = extra.get("s3_access_key_id") or extra.get("aws_access_key_id")
            secret = extra.get("s3_secret_access_key") or extra.get("aws_secret_access_key")
            region = extra.get("s3_region") or extra.get("aws_region") or "us-east-1"
            provider = str(extra.get("s3_provider") or extra.get("aws_provider") or "").strip().lower()
            endpoint = extra.get("s3_endpoint")
            url_style = extra.get("s3_url_style") or extra.get("url_style")
            use_ssl = _bool_extra(extra.get("s3_use_ssl"), default=not bool(endpoint))

            if provider:
                secret_parts = [
                    "TYPE s3",
                    "PROVIDER " + provider,
                    "REGION " + _quote_sql_literal(region),
                ]
                if endpoint:
                    endpoint_value = str(endpoint)
                    endpoint_value = endpoint_value.removeprefix("http://").removeprefix("https://")
                    secret_parts.append("ENDPOINT " + _quote_sql_literal(endpoint_value))
                if url_style:
                    secret_parts.append("URL_STYLE " + _quote_sql_literal(url_style))
                secret_parts.append("USE_SSL " + ("true" if use_ssl else "false"))
                con.execute("CREATE OR REPLACE SECRET datus_s3 (" + ", ".join(secret_parts) + ")")
            elif key_id and secret:
                secret_parts = [
                    "TYPE s3",
                    "KEY_ID " + _quote_sql_literal(key_id),
                    "SECRET " + _quote_sql_literal(secret),
                    "REGION " + _quote_sql_literal(region),
                ]
                if endpoint:
                    endpoint_value = str(endpoint)
                    endpoint_value = endpoint_value.removeprefix("http://").removeprefix("https://")
                    secret_parts.append("ENDPOINT " + _quote_sql_literal(endpoint_value))
                if url_style:
                    secret_parts.append("URL_STYLE " + _quote_sql_literal(url_style))
                secret_parts.append("USE_SSL " + ("true" if use_ssl else "false"))
                con.execute("CREATE OR REPLACE SECRET datus_s3 (" + ", ".join(secret_parts) + ")")

            attach_options = [
                "TYPE iceberg",
                "ENDPOINT " + _quote_sql_literal(catalog_uri),
            ]
            if iceberg_secret_name:
                attach_options.append("SECRET " + iceberg_secret_name)

            option_aliases = {{
                "endpoint_type": "ENDPOINT_TYPE",
                "default_region": "DEFAULT_REGION",
                "authorization_type": "AUTHORIZATION_TYPE",
                "access_delegation_mode": "ACCESS_DELEGATION_MODE",
                "support_nested_namespaces": "SUPPORT_NESTED_NAMESPACES",
                "support_stage_create": "SUPPORT_STAGE_CREATE",
                "max_table_staleness": "MAX_TABLE_STALENESS",
                "purge_requested": "PURGE_REQUESTED",
            }}
            has_catalog_auth = bool(
                iceberg_secret_name
                or extra.get("authorization_type")
                or extra.get("endpoint_type")
                or extra.get("client_id")
                or extra.get("client_secret")
                or extra.get("token")
            )
            if not has_catalog_auth:
                if not extra.get("authorization_type"):
                    attach_options.append("AUTHORIZATION_TYPE none")
                if not extra.get("access_delegation_mode"):
                    attach_options.append("ACCESS_DELEGATION_MODE none")
            for cfg_key, sql_name in option_aliases.items():
                option = _sql_option(sql_name, extra.get(cfg_key))
                if option:
                    attach_options.append(option)
            attach_options.append(
                "READ_ONLY " + ("true" if _bool_extra(extra.get("read_only"), default=False) else "false")
            )
            con.execute(
                "ATTACH " + _quote_sql_literal(warehouse) + " AS " + catalog_alias + " ("
                + ", ".join(attach_options)
                + ")"
            )

            result = con.execute(_rewrite_iceberg_create_or_replace_table(sql))
            if result.description:
                columns = [col[0] for col in result.description]
                rows = result.fetchmany(50)
                print("[Datus] DuckDB Iceberg SQL completed. preview_rows=" + str(len(rows)))
                if columns:
                    print("[Datus] Columns: " + " | ".join(str(c) for c in columns))
                for i, row in enumerate(rows):
                    print("[Datus] Row " + str(i + 1) + ": " + " | ".join(str(v) for v in row))
                return {{"status": "success", "row_count": len(rows)}}

            print("[Datus] DuckDB Iceberg SQL completed.")
            return {{"status": "success", "row_count": 0}}
        finally:
            con.close()


    def _execute_datus_sql(**context: dict) -> dict:  # noqa: ANN001
        """Execute the SQL configured by Datus."""
        cfg: dict = _DATUS_CONFIG
        sql: str = cfg["sql"]
        db_connection: dict = cfg.get("db_connection") or {{}}

        print("[Datus] Running SQL: " + sql[:200])

        if _is_duckdb_iceberg_connection(db_connection):
            return _execute_duckdb_iceberg_sql(sql, db_connection)

        connection_url: str | None = _resolve_connection_url(db_connection)
        if connection_url:
            from sqlalchemy import create_engine, text  # noqa: PLC0415

            engine = create_engine(connection_url)
            columns: list = []
            rows: list = []
            has_more = False
            affected: int = -1
            with engine.connect() as conn:
                result = conn.execute(text(sql))
                returns_rows = result.returns_rows
                if returns_rows:
                    columns = list(result.keys())
                    rows = result.fetchmany(50)
                    has_more = bool(result.fetchone())
                else:
                    affected = result.rowcount if result.rowcount is not None else -1

            if returns_rows:
                row_count = len(rows)
                print(
                    "[Datus] SQL completed. preview_rows="
                    + str(row_count)
                    + (", has_more=True" if has_more else "")
                )
                if columns:
                    print("[Datus] Columns: " + " | ".join(str(c) for c in columns))
                for i, row in enumerate(rows):
                    print("[Datus] Row " + str(i + 1) + ": " + " | ".join(str(v) for v in row))
                if has_more:
                    print("[Datus] ... (more rows available, preview limited to 50)")
            else:
                row_count = affected if affected >= 0 else 0
                affected_display = str(affected) if affected >= 0 else "unknown"
                print("[Datus] SQL completed (no rowset). affected_rows=" + affected_display)

            return {{"status": "success", "row_count": row_count}}

        # No connection configured — succeed with a warning (useful for dry-run / test DAGs).
        print("[Datus] No connection configured; skipping SQL execution.")
        return {{"status": "skipped"}}


    with DAG(
        dag_id={dag_id_repr},
        description={description_repr},
        schedule={schedule_repr},
        start_date=datetime({start_year}, {start_month}, {start_day}, tzinfo=timezone.utc),
        end_date={end_date_repr},
        catchup=False,
        tags=["datus"],
        is_paused_upon_creation=False,
    ) as dag:
        execute_sql = PythonOperator(
            task_id="execute_sql",
            python_callable=_execute_datus_sql,
        )
    '''
)


def render_spark_dag_source(
    dag_id: str,
    job_name: str,
    spark_script: str,
    spark_master: str = "local[*]",
    schedule: Optional[str] = None,
    start_date: Optional[datetime] = None,
    description: Optional[str] = None,
) -> str:
    """Render a Python DAG source string for a generic PySpark script.

    Args:
        dag_id:       Airflow DAG identifier (must be unique across all DAGs).
        job_name:     Human-readable name (embedded as a comment).
        spark_script: Inline PySpark script; ``sc`` (SparkContext) is injected.
        spark_master: Spark master URL, e.g. ``local[*]`` or ``spark://host:7077``.
        schedule:     Cron expression or ``None`` for manual-only.
        start_date:   DAG start date; defaults to 2024-01-01 UTC when ``None``.
        description:  Optional DAG description.

    Returns:
        A string containing valid Python source code for an Airflow DAG file.
    """
    logger.warning(
        "Rendering Spark DAG '%s' with inline script execution (exec()). Ensure the spark_script source is trusted.",
        dag_id,
    )

    config_payload = {
        "spark_script": spark_script,
        "spark_master": spark_master or "local[*]",
    }
    config_json = json.dumps(config_payload, ensure_ascii=False, indent=4)

    effective_start = start_date or datetime(2024, 1, 1, tzinfo=timezone.utc)

    effective_schedule = schedule if schedule and str(schedule).strip().lower() != "none" else None

    return _SPARK_DAG_TEMPLATE.format(
        job_name=job_name,
        built_at=datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        config_json=config_json,
        dag_id_repr=repr(dag_id),
        description_repr=repr(description or f"Datus Spark job: {job_name}"),
        schedule_repr=repr(effective_schedule),
        start_year=effective_start.year,
        start_month=effective_start.month,
        start_day=effective_start.day,
        end_date_repr="None",
    )


_SPARKSQL_DAG_TEMPLATE = textwrap.dedent(
    '''\
    # ============================================================
    # Auto-generated by Datus Airflow Adapter — DO NOT EDIT
    # Job  : {job_name}
    # Built: {built_at}
    # ============================================================

    from __future__ import annotations

    import json
    from datetime import datetime, timezone

    from airflow import DAG
    from airflow.operators.python import PythonOperator

    _SPARKSQL_CONFIG: dict = {config_json}


    def _run_sparksql(**context: dict) -> dict:  # noqa: ANN001
        """Execute SparkSQL configured by Datus."""
        from pyspark.sql import SparkSession  # noqa: PLC0415

        spark = (
            SparkSession.builder
            .master(_SPARKSQL_CONFIG["spark_master"])
            .appName("DatusSparkSQL")
            .getOrCreate()
        )
        sql: str = _SPARKSQL_CONFIG["sql"]
        print("[Datus] Running SparkSQL: " + sql[:200])
        result = spark.sql(sql)
        count = result.count()
        print("[Datus] SparkSQL completed. rows=" + str(count))
        spark.stop()
        return {{"status": "success", "row_count": count}}


    with DAG(
        dag_id={dag_id_repr},
        description={description_repr},
        schedule={schedule_repr},
        start_date=datetime({start_year}, {start_month}, {start_day}, tzinfo=timezone.utc),
        end_date={end_date_repr},
        catchup=False,
        tags=["datus", "sparksql"],
        is_paused_upon_creation=False,
    ) as dag:
        run_sparksql = PythonOperator(
            task_id="run_sparksql",
            python_callable=_run_sparksql,
        )
    '''
)


def render_sparksql_dag_source(
    dag_id: str,
    job_name: str,
    sql: str,
    spark_master: str = "local[*]",
    schedule: Optional[str] = None,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    description: Optional[str] = None,
) -> str:
    """Render a Python DAG source string for a SparkSQL query.

    The generated DAG creates a SparkSession and runs the SQL via
    ``spark.sql()``, which supports the full SparkSQL dialect.

    Args:
        dag_id:       Airflow DAG identifier (must be unique across all DAGs).
        job_name:     Human-readable name (embedded as a comment).
        sql:          SparkSQL statement to execute.
        spark_master: Spark master URL, e.g. ``local[*]`` or ``spark://host:7077``.
        schedule:     Cron expression or ``None`` for manual-only.
        start_date:   DAG start date; defaults to 2024-01-01 UTC when ``None``.
        end_date:     Optional DAG end date.
        description:  Optional DAG description.

    Returns:
        A string containing valid Python source code for an Airflow DAG file.
    """
    config_payload = {
        "sql": sql,
        "spark_master": spark_master or "local[*]",
    }
    config_json = json.dumps(config_payload, ensure_ascii=False, indent=4)

    effective_start = start_date or datetime(2024, 1, 1, tzinfo=timezone.utc)
    end_date_repr = (
        f"datetime({end_date.year}, {end_date.month}, {end_date.day}, tzinfo=timezone.utc)" if end_date else "None"
    )

    effective_schedule = schedule if schedule and str(schedule).strip().lower() != "none" else None

    return _SPARKSQL_DAG_TEMPLATE.format(
        job_name=job_name,
        built_at=datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        config_json=config_json,
        dag_id_repr=repr(dag_id),
        description_repr=repr(description or f"Datus SparkSQL job: {job_name}"),
        schedule_repr=repr(effective_schedule),
        start_year=effective_start.year,
        start_month=effective_start.month,
        start_day=effective_start.day,
        end_date_repr=end_date_repr,
    )


def render_dag_source(
    dag_id: str,
    job_name: str,
    sql: str,
    db_connection: Optional[dict],
    schedule: Optional[str],
    start_date: Optional[datetime],
    end_date: Optional[datetime],
    description: Optional[str],
) -> str:
    """Render a Python DAG source string from the template.

    Args:
        dag_id:        Airflow DAG identifier (must be unique across all DAGs).
        job_name:      Human-readable name (embedded as a comment).
        sql:           SQL statement to execute.
        db_connection: Dict with at least a ``url`` key (SQLAlchemy connection URL).
        schedule:      Cron expression or ``None`` for manual-only.
        start_date:    DAG start date; defaults to 2024-01-01 UTC when ``None``.
        end_date:      Optional DAG end date.
        description:   Optional DAG description.

    Returns:
        A string containing valid Python source code for an Airflow DAG file.
    """
    # Warn if db_connection contains a raw URL with potential credentials
    if db_connection and "url" in db_connection:
        url = db_connection["url"]
        if "@" in str(url) and "://" in str(url):
            logger.warning(
                "db_connection contains a URL with possible inline credentials. "
                "Consider using conn_id (Airflow Connection) instead to avoid writing secrets to DAG files."
            )

    config_payload = {
        "sql": sql,
        "db_connection": db_connection or {},
    }
    config_json = json.dumps(config_payload, ensure_ascii=False, indent=4)

    effective_start = start_date or datetime(2024, 1, 1, tzinfo=timezone.utc)
    end_date_repr = (
        f"datetime({end_date.year}, {end_date.month}, {end_date.day}, tzinfo=timezone.utc)" if end_date else "None"
    )

    effective_schedule = schedule if schedule and str(schedule).strip().lower() != "none" else None

    return _DAG_TEMPLATE.format(
        job_name=job_name,
        built_at=datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        config_json=config_json,
        dag_id_repr=repr(dag_id),
        description_repr=repr(description or f"Datus job: {job_name}"),
        schedule_repr=repr(effective_schedule),
        start_year=effective_start.year,
        start_month=effective_start.month,
        start_day=effective_start.day,
        end_date_repr=end_date_repr,
    )
